server:
  port: 8088
eureka:
  instance:
    hostname: registry1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://registry2:8089/eureka/

