server:
  port: 8088
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: registry1
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8089/eureka/
spring:
  application:
    name: eureka-server1
