server:
  port: 8089
eureka:
  instance:
    hostname: registry2
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://registry1:8088/eureka/


